"""
api/config.py
-----------------------------------------------------------------------
API CONFIGURATION

Uses pydantic-settings to load config from environment variables
or a .env file. This is the same pattern used in production APIs —
no hardcoded values anywhere in the codebase.

USAGE:
    Copy api/.env.example to api/.env and fill in your values.
    The settings object is imported wherever config is needed.

WHY PYDANTIC SETTINGS?
    - Type-validated config (wrong types raise clear errors at startup)
    - Automatic .env file loading
    - Works identically in dev and prod — just swap the .env file
    - Consistent with the OOP patterns already in this project
-----------------------------------------------------------------------
"""

from pydantic_settings import BaseSettings
from enum import Enum
from typing import Optional


class DataBackend(str, Enum):
    """
    Which data backend the API reads from.
    Mirrors the Databricks/Fabric switching pattern in the dbt layer.
    """
    DUCKDB = "duckdb"           # Local dev — no cloud needed
    DATABRICKS = "databricks"   # Live Databricks mart tables


class Settings(BaseSettings):
    """
    All configuration for the GraphQL API.
    Values are loaded from environment variables or api/.env
    """

    # ------------------------------------------------------------------
    # API settings
    # ------------------------------------------------------------------
    api_title: str = "E-Commerce Analytics GraphQL API"
    api_version: str = "0.1.0"
    debug: bool = True
    host: str = "127.0.0.1"
    port: int = 8000

    # ------------------------------------------------------------------
    # Data backend
    # Switch between local DuckDB and live Databricks with one change
    # ------------------------------------------------------------------
    data_backend: DataBackend = DataBackend.DUCKDB

    # ------------------------------------------------------------------
    # DuckDB settings (local dev)
    # Points at the data/bronze CSVs generated by generate_sample_data.py
    # After running dbt locally you can also point at parquet exports
    # ------------------------------------------------------------------
    duckdb_data_path: str = "data/bronze"   # Relative to project root

    # ------------------------------------------------------------------
    # Databricks settings (prod)
    # Same values as your dbt profiles.yml
    # ------------------------------------------------------------------
    databricks_host: Optional[str] = None
    databricks_http_path: Optional[str] = None
    databricks_token: Optional[str] = None
    databricks_catalog: str = "hive_metastore"
    databricks_schema: str = "marts"

    # ------------------------------------------------------------------
    # Query limits — prevent runaway queries in the POC
    # ------------------------------------------------------------------
    default_limit: int = 100
    max_limit: int = 1000

    class Config:
        env_file = "api/.env"
        env_file_encoding = "utf-8"


# Singleton — import this anywhere you need config
settings = Settings()
